name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up environment variables
        run: echo "APP_KEY=base64:$(openssl rand -base64 32)" >> $GITHUB_ENV
        env:
          APP_KEY: ${{ secrets.APP_KEY }}

      - name: Set up database
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test --env=testing

    # deploy (Commented out the CD part, since you don't have a server to deploy changes to):
    # runs-on: ubuntu-latest
    # needs: ci
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3
    #   - name: Deploy to production
    #     run: |
    #       ssh user@server "cd /path/to/project && git pull && composer install && php artisan migrate"
