name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # выполняется при пуше в ветку main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Composer dependencies
        run: composer install

      - name: Run tests
        run: php artisan test

  #deploy (Commented out the CD part, since I don't have a server to deliver my changes to):
    #runs-on: ubuntu-latest
    #needs: ci

    #steps:
      #- name: Checkout code
        #uses: actions/checkout@v3

      #- name: Deploy to production
        #run: |
          #ssh user@server "cd /path/to/project && git pull && composer install && php artisan migrate"
